version: "3.8"

services:
  db:
    image: postgres:17.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=milan
      - POSTGRES_DB=ems
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: deps
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:milan@localhost:5432/ems?schema=public
volumes:
  postgres_data:
