version: "3.8"

services:
  db:
    image: postgres17.2
    ports:
      - 5432:5432

  app:
    build:
      context: .
      target: deps
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
